-- NS DemoHelper MVP APEX database logging.
-- Replace the admin password hash placeholder before applying in the APEX workspace.
-- This script creates flexible logging tables plus ORDS endpoints under:
--   /pls/apex/emeawj/nsdh

set define off

declare
  procedure run_ddl(p_sql in clob) is
  begin
    execute immediate p_sql;
  exception
    when others then
      if sqlcode not in (-955, -1408, -1430, -2260, -2275) then
        raise;
      end if;
  end;
begin
  run_ddl(q'[
    create table nsdh_sessions (
      id number generated by default on null as identity primary key,
      session_id varchar2(128) not null,
      anonymous_user_id varchar2(128),
      created_at timestamp with time zone default systimestamp not null,
      updated_at timestamp with time zone default systimestamp not null,
      app_version varchar2(64),
      environment varchar2(64),
      runtime_mode varchar2(64),
      source_page varchar2(128),
      browser_user_agent varchar2(1000),
      company_name varchar2(500),
      website varchar2(1000),
      audience_type varchar2(255),
      target_segment varchar2(255),
      industry varchar2(255),
      demo_strategy varchar2(255),
      discovery_score number,
      demo_readiness_score number,
      risk_score number,
      generation_status varchar2(64),
      error_message varchar2(4000),
      active_ai_provider varchar2(255),
      payload_json clob check (payload_json is json),
      constraint nsdh_sessions_sid_uk unique (session_id)
    )
  ]');

  run_ddl(q'[
    create table nsdh_session_inputs (
      id number generated by default on null as identity primary key,
      session_id varchar2(128) not null,
      created_at timestamp with time zone default systimestamp not null,
      source_action varchar2(255),
      payload_json clob check (payload_json is json)
    )
  ]');

  run_ddl(q'[
    create table nsdh_score_results (
      id number generated by default on null as identity primary key,
      session_id varchar2(128) not null,
      created_at timestamp with time zone default systimestamp not null,
      discovery_score number,
      demo_readiness_score number,
      risk_score number,
      gaps_json clob check (gaps_json is json),
      recommendations_json clob check (recommendations_json is json),
      payload_json clob check (payload_json is json)
    )
  ]');

  run_ddl(q'[
    create table nsdh_generated_outputs (
      id number generated by default on null as identity primary key,
      session_id varchar2(128) not null,
      created_at timestamp with time zone default systimestamp not null,
      output_type varchar2(128),
      generation_status varchar2(64),
      payload_json clob check (payload_json is json)
    )
  ]');

  run_ddl(q'[
    create table nsdh_event_log (
      id number generated by default on null as identity primary key,
      session_id varchar2(128),
      anonymous_user_id varchar2(128),
      created_at timestamp with time zone default systimestamp not null,
      source_page varchar2(128),
      action varchar2(255),
      status varchar2(64),
      error_code varchar2(128),
      error_message varchar2(4000),
      duration_ms number,
      payload_json clob check (payload_json is json)
    )
  ]');

  run_ddl(q'[
    create table nsdh_admin_settings (
      setting_name varchar2(128) primary key,
      setting_value varchar2(4000) not null,
      updated_at timestamp with time zone default systimestamp not null
    )
  ]');

  run_ddl(q'[
    create table nsdh_admin_tokens (
      token_hash varchar2(128) primary key,
      created_at timestamp with time zone default systimestamp not null,
      expires_at timestamp with time zone not null
    )
  ]');

  run_ddl('create index nsdh_sessions_updated_ix on nsdh_sessions(updated_at desc)');
  run_ddl('create index nsdh_sessions_company_ix on nsdh_sessions(company_name)');
  run_ddl('create index nsdh_inputs_session_ix on nsdh_session_inputs(session_id)');
  run_ddl('create index nsdh_scores_session_ix on nsdh_score_results(session_id)');
  run_ddl('create index nsdh_outputs_session_ix on nsdh_generated_outputs(session_id)');
  run_ddl('create index nsdh_events_session_ix on nsdh_event_log(session_id)');
end;
/

merge into nsdh_admin_settings s
using (
  select 'ADMIN_PASSWORD_SHA256' setting_name,
         '__ADMIN_PASSWORD_SHA256__' setting_value
  from dual
) src
on (s.setting_name = src.setting_name)
when matched then update set s.setting_value = src.setting_value, s.updated_at = systimestamp
when not matched then insert (setting_name, setting_value) values (src.setting_name, src.setting_value)
/

create or replace package nsdh_log_api authid definer as
  procedure log_session(p_payload in clob, p_response out clob, p_status out number);
  procedure admin_login(p_payload in clob, p_response out clob, p_status out number);
  procedure admin_logout(p_token in varchar2, p_response out clob, p_status out number);
  procedure list_sessions(
    p_search in varchar2,
    p_filter_status in varchar2,
    p_audience in varchar2,
    p_strategy in varchar2,
    p_sort in varchar2,
    p_admin_token in varchar2,
    p_response out clob,
    p_status out number
  );
  procedure get_session(p_session_id in varchar2, p_admin_token in varchar2, p_response out clob, p_status out number);
  procedure delete_session(p_session_id in varchar2, p_admin_token in varchar2, p_response out clob, p_status out number);
end nsdh_log_api;
/

create or replace package body nsdh_log_api as
  function jstr(p_payload in clob, p_path in varchar2) return varchar2 is
    l_value varchar2(4000);
  begin
    l_value := json_value(p_payload, p_path returning varchar2(4000) null on error);
    return substr(l_value, 1, 4000);
  exception
    when others then
      return null;
  end;

  function jnum(p_payload in clob, p_path in varchar2) return number is
    l_value number;
  begin
    l_value := json_value(p_payload, p_path returning number null on error);
    return l_value;
  exception
    when others then
      return null;
  end;

  function jclob(p_payload in clob, p_path in varchar2) return clob is
    l_value clob;
  begin
    l_value := json_query(p_payload, p_path returning clob null on error);
    return l_value;
  exception
    when others then
      return null;
  end;

  function clean_id(p_value in varchar2) return varchar2 is
  begin
    return substr(regexp_replace(nvl(p_value, ''), '[^A-Za-z0-9_-]', ''), 1, 96);
  end;

  function utc_text(p_value in timestamp with time zone) return varchar2 is
  begin
    return to_char(p_value at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"');
  end;

  function has_sensitive_keys(p_payload in clob) return boolean is
    l_probe varchar2(32767);
  begin
    l_probe := lower(dbms_lob.substr(p_payload, 32767, 1));
    return regexp_like(l_probe, '"([^"]*(password|api.?key|secret|token|credential|authorization|cookie)[^"]*)"\s*:');
  end;

  function admin_hash return varchar2 is
    l_hash varchar2(4000);
  begin
    select setting_value into l_hash
    from nsdh_admin_settings
    where setting_name = 'ADMIN_PASSWORD_SHA256';
    return upper(l_hash);
  exception
    when no_data_found then
      return null;
  end;

  function sha256_hex(p_value in varchar2) return varchar2 is
    l_hash varchar2(4000);
  begin
    select standard_hash(nvl(p_value, ''), 'SHA256') into l_hash from dual;
    return upper(l_hash);
  end;

  function is_admin(p_token in varchar2) return boolean is
    l_count number;
    l_token_hash varchar2(4000);
  begin
    delete from nsdh_admin_tokens where expires_at < systimestamp;
    if p_token is null then
      return false;
    end if;
    l_token_hash := sha256_hex(p_token);
    select count(*) into l_count
    from nsdh_admin_tokens
    where token_hash = l_token_hash
      and expires_at >= systimestamp;
    return l_count > 0;
  end;

  function error_json(p_message in varchar2, p_code in varchar2 default null) return clob is
  begin
    return '{"ok":false,"error":' || apex_json.stringify(p_message) ||
      case when p_code is not null then ',"code":' || apex_json.stringify(p_code) else '' end || '}';
  end;

  procedure log_session(p_payload in clob, p_response out clob, p_status out number) is
    l_session_id varchar2(128);
    l_event clob;
    l_inputs clob;
    l_scores clob;
    l_outputs clob;
    l_is_json boolean := false;
    l_anonymous_user_id varchar2(128);
    l_app_version varchar2(64);
    l_environment varchar2(64);
    l_runtime_mode varchar2(64);
    l_source_page varchar2(128);
    l_browser_user_agent varchar2(1000);
    l_company_name varchar2(500);
    l_website varchar2(1000);
    l_audience_type varchar2(255);
    l_target_segment varchar2(255);
    l_industry varchar2(255);
    l_demo_strategy varchar2(255);
    l_discovery_score number;
    l_demo_readiness_score number;
    l_risk_score number;
    l_generation_status varchar2(64);
    l_error_message varchar2(4000);
    l_active_ai_provider varchar2(255);
    l_action varchar2(255);
    l_gaps clob;
    l_recommendations clob;
    l_duration_ms number;
  begin
    p_status := 200;
    if p_payload is not null then
      begin
        l_is_json := json_exists(p_payload, '$');
      exception
        when others then
          l_is_json := false;
      end;
    end if;
    if p_payload is null or not l_is_json then
      p_status := 400;
      p_response := error_json('Session payload must be valid JSON.', 'INVALID_JSON');
      return;
    end if;
    if has_sensitive_keys(p_payload) then
      p_status := 400;
      p_response := error_json('Session payload contains a sensitive key and was not logged.', 'SENSITIVE_FIELD_REJECTED');
      return;
    end if;

    l_session_id := clean_id(jstr(p_payload, '$.session_id'));
    if l_session_id is null then
      l_session_id := 'session_' || lower(rawtohex(sys_guid()));
    end if;
    l_anonymous_user_id := clean_id(jstr(p_payload, '$.anonymous_user_id'));
    l_app_version := jstr(p_payload, '$.app_version');
    l_environment := jstr(p_payload, '$.environment');
    l_runtime_mode := jstr(p_payload, '$.mode');
    l_source_page := jstr(p_payload, '$.source_page');
    l_browser_user_agent := jstr(p_payload, '$.browser_user_agent');
    l_company_name := jstr(p_payload, '$.company_name');
    l_website := jstr(p_payload, '$.website');
    l_audience_type := jstr(p_payload, '$.audience_type');
    l_target_segment := jstr(p_payload, '$.target_segment');
    l_industry := jstr(p_payload, '$.industry');
    l_demo_strategy := jstr(p_payload, '$.demo_strategy');
    l_discovery_score := jnum(p_payload, '$.discovery_score');
    l_demo_readiness_score := jnum(p_payload, '$.demo_readiness_score');
    l_risk_score := jnum(p_payload, '$.risk_score');
    l_generation_status := jstr(p_payload, '$.generation_status');
    l_error_message := jstr(p_payload, '$.error_message');
    l_active_ai_provider := jstr(p_payload, '$.provider_backbone.activeProvider.name');
    l_action := jstr(p_payload, '$.action');
    l_gaps := coalesce(jclob(p_payload, '$.identified_gaps'), '[]');
    l_recommendations := coalesce(jclob(p_payload, '$.recommendations'), '[]');
    l_duration_ms := jnum(p_payload, '$.duration_ms');

    merge into nsdh_sessions s
    using (
      select
        l_session_id session_id,
        l_anonymous_user_id anonymous_user_id,
        l_app_version app_version,
        l_environment environment,
        l_runtime_mode runtime_mode,
        l_source_page source_page,
        l_browser_user_agent browser_user_agent,
        l_company_name company_name,
        l_website website,
        l_audience_type audience_type,
        l_target_segment target_segment,
        l_industry industry,
        l_demo_strategy demo_strategy,
        l_discovery_score discovery_score,
        l_demo_readiness_score demo_readiness_score,
        l_risk_score risk_score,
        l_generation_status generation_status,
        l_error_message error_message,
        l_active_ai_provider active_ai_provider
      from dual
    ) src
    on (s.session_id = src.session_id)
    when matched then update set
      s.updated_at = systimestamp,
      s.anonymous_user_id = coalesce(src.anonymous_user_id, s.anonymous_user_id),
      s.app_version = coalesce(src.app_version, s.app_version),
      s.environment = coalesce(src.environment, s.environment),
      s.runtime_mode = coalesce(src.runtime_mode, s.runtime_mode),
      s.source_page = coalesce(src.source_page, s.source_page),
      s.browser_user_agent = coalesce(src.browser_user_agent, s.browser_user_agent),
      s.company_name = coalesce(src.company_name, s.company_name),
      s.website = coalesce(src.website, s.website),
      s.audience_type = coalesce(src.audience_type, s.audience_type),
      s.target_segment = coalesce(src.target_segment, s.target_segment),
      s.industry = coalesce(src.industry, s.industry),
      s.demo_strategy = coalesce(src.demo_strategy, s.demo_strategy),
      s.discovery_score = coalesce(src.discovery_score, s.discovery_score),
      s.demo_readiness_score = coalesce(src.demo_readiness_score, s.demo_readiness_score),
      s.risk_score = coalesce(src.risk_score, s.risk_score),
      s.generation_status = coalesce(src.generation_status, s.generation_status),
      s.error_message = coalesce(src.error_message, s.error_message),
      s.active_ai_provider = coalesce(src.active_ai_provider, s.active_ai_provider),
      s.payload_json = p_payload
    when not matched then insert (
      session_id, anonymous_user_id, app_version, environment, runtime_mode, source_page,
      browser_user_agent, company_name, website, audience_type, target_segment, industry,
      demo_strategy, discovery_score, demo_readiness_score, risk_score, generation_status,
      error_message, active_ai_provider, payload_json
    ) values (
      src.session_id, src.anonymous_user_id, src.app_version, src.environment, src.runtime_mode,
      src.source_page, src.browser_user_agent, src.company_name, src.website, src.audience_type,
      src.target_segment, src.industry, src.demo_strategy, src.discovery_score,
      src.demo_readiness_score, src.risk_score, src.generation_status, src.error_message,
      src.active_ai_provider, p_payload
    );

    l_inputs := jclob(p_payload, '$.input_context');
    if l_inputs is not null then
      insert into nsdh_session_inputs(session_id, source_action, payload_json)
      values (l_session_id, l_action, l_inputs);
    end if;

    select json_object(
        'discovery_score' value l_discovery_score,
        'demo_readiness_score' value l_demo_readiness_score,
        'risk_score' value l_risk_score
        returning clob
      )
      into l_scores
      from dual;
    insert into nsdh_score_results(session_id, discovery_score, demo_readiness_score, risk_score, gaps_json, recommendations_json, payload_json)
    values (
      l_session_id,
      l_discovery_score,
      l_demo_readiness_score,
      l_risk_score,
      l_gaps,
      l_recommendations,
      l_scores
    );

    l_outputs := jclob(p_payload, '$.generated_outputs');
    if l_outputs is not null then
      insert into nsdh_generated_outputs(session_id, output_type, generation_status, payload_json)
      values (l_session_id, l_action, l_generation_status, l_outputs);
    end if;

    l_event := jclob(p_payload, '$.event');
    if l_event is null then
      select json_object('action' value l_action returning clob)
        into l_event
        from dual;
    end if;
    insert into nsdh_event_log(session_id, anonymous_user_id, source_page, action, status, error_message, duration_ms, payload_json)
    values (
      l_session_id,
      l_anonymous_user_id,
      l_source_page,
      l_action,
      l_generation_status,
      l_error_message,
      l_duration_ms,
      l_event
    );

    commit;
    p_response := '{"ok":true,"session_id":' || apex_json.stringify(l_session_id) || '}';
  exception
    when others then
      rollback;
      p_status := 500;
      p_response := error_json(sqlerrm, 'LOGGING_FAILED');
  end log_session;

  procedure admin_login(p_payload in clob, p_response out clob, p_status out number) is
    l_password varchar2(4000);
    l_token varchar2(128);
    l_token_hash varchar2(4000);
  begin
    p_status := 200;
    l_password := json_value(p_payload, '$.password' returning varchar2(4000) null on error);
    if admin_hash is null or sha256_hex(l_password) <> admin_hash then
      p_status := 401;
      p_response := error_json('Invalid admin password.', 'ADMIN_AUTH_FAILED');
      return;
    end if;
    l_token := lower(rawtohex(sys_guid()) || rawtohex(sys_guid()));
    l_token_hash := sha256_hex(l_token);
    insert into nsdh_admin_tokens(token_hash, expires_at)
    values (l_token_hash, systimestamp + interval '8' hour);
    commit;
    p_response := '{"ok":true,"adminSessionToken":' || apex_json.stringify(l_token) || '}';
  exception
    when others then
      rollback;
      p_status := 500;
      p_response := error_json(sqlerrm, 'ADMIN_LOGIN_FAILED');
  end admin_login;

  procedure admin_logout(p_token in varchar2, p_response out clob, p_status out number) is
    l_token_hash varchar2(4000) := sha256_hex(nvl(p_token, ''));
  begin
    p_status := 200;
    delete from nsdh_admin_tokens where token_hash = l_token_hash;
    commit;
    p_response := '{"ok":true}';
  end admin_logout;

  procedure list_sessions(
    p_search in varchar2,
    p_filter_status in varchar2,
    p_audience in varchar2,
    p_strategy in varchar2,
    p_sort in varchar2,
    p_admin_token in varchar2,
    p_response out clob,
    p_status out number
  ) is
    l_total number;
    l_success number;
    l_failed number;
    l_avg_discovery number;
    l_avg_readiness number;
    l_search varchar2(4000) := lower(trim(p_search));
    l_status varchar2(4000) := lower(trim(p_filter_status));
    l_audience varchar2(4000) := lower(trim(p_audience));
    l_strategy varchar2(4000) := lower(trim(p_strategy));
    l_sort varchar2(100) := lower(nvl(p_sort, 'updated_desc'));
  begin
    if not is_admin(p_admin_token) then
      p_status := 401;
      p_response := error_json('Admin unlock is required to view saved sessions.', 'ADMIN_AUTH_REQUIRED');
      return;
    end if;
    p_status := 200;

    select count(*),
           sum(case when generation_status = 'success' then 1 else 0 end),
           sum(case when generation_status = 'failed' then 1 else 0 end),
           round(avg(discovery_score)),
           round(avg(demo_readiness_score))
      into l_total, l_success, l_failed, l_avg_discovery, l_avg_readiness
      from nsdh_sessions;

    apex_json.initialize_clob_output;
    apex_json.open_object;
    apex_json.write('ok', true);
    apex_json.write('generatedAt', utc_text(systimestamp));
    apex_json.write('total', l_total);
    apex_json.open_object('metrics');
    apex_json.write('total_sessions', l_total);
    apex_json.write('successful_sessions', nvl(l_success, 0));
    apex_json.write('failed_sessions', nvl(l_failed, 0));
    apex_json.write('average_discovery_score', l_avg_discovery);
    apex_json.write('average_demo_readiness_score', l_avg_readiness);
    apex_json.close_object;
    apex_json.open_array('sessions');
    for r in (
      select *
      from nsdh_sessions
      where (l_search is null or lower(company_name || ' ' || website || ' ' || audience_type || ' ' || target_segment || ' ' || industry || ' ' || demo_strategy || ' ' || generation_status) like '%' || l_search || '%')
        and (l_status is null or lower(generation_status) = l_status)
        and (l_audience is null or lower(audience_type) = l_audience)
        and (l_strategy is null or lower(demo_strategy) = l_strategy)
      order by
        case when l_sort = 'readiness_desc' then demo_readiness_score end desc nulls last,
        case when l_sort = 'discovery_desc' then discovery_score end desc nulls last,
        case when l_sort = 'created_desc' then created_at end desc nulls last,
        updated_at desc
      fetch first 250 rows only
    ) loop
      apex_json.open_object;
      apex_json.write('session_id', r.session_id);
      apex_json.write('company_name', r.company_name);
      apex_json.write('website', r.website);
      apex_json.write('audience_type', r.audience_type);
      apex_json.write('target_segment', r.target_segment);
      apex_json.write('industry', r.industry);
      apex_json.write('demo_strategy', r.demo_strategy);
      apex_json.write('discovery_score', r.discovery_score);
      apex_json.write('demo_readiness_score', r.demo_readiness_score);
      apex_json.write('risk_score', r.risk_score);
      apex_json.write('generation_timestamp', utc_text(r.updated_at));
      apex_json.write('created_at', utc_text(r.created_at));
      apex_json.write('updated_at', utc_text(r.updated_at));
      apex_json.write('active_ai_provider', nvl(r.active_ai_provider, 'Codex'));
      apex_json.write('session_status', nvl(r.generation_status, 'unknown'));
      apex_json.close_object;
    end loop;
    apex_json.close_array;
    apex_json.close_object;
    p_response := apex_json.get_clob_output;
    apex_json.free_output;
  exception
    when others then
      apex_json.free_output;
      p_status := 500;
      p_response := error_json(sqlerrm, 'SESSION_LIST_FAILED');
  end list_sessions;

  procedure get_session(p_session_id in varchar2, p_admin_token in varchar2, p_response out clob, p_status out number) is
    l_payload clob;
    l_session_id varchar2(128) := clean_id(p_session_id);
  begin
    if not is_admin(p_admin_token) then
      p_status := 401;
      p_response := error_json('Admin unlock is required to view saved sessions.', 'ADMIN_AUTH_REQUIRED');
      return;
    end if;
    select payload_json into l_payload
    from nsdh_sessions
    where session_id = l_session_id;
    p_status := 200;
    p_response := '{"ok":true,"session":' || l_payload || '}';
  exception
    when no_data_found then
      p_status := 404;
      p_response := error_json('Session was not found.', 'SESSION_NOT_FOUND');
    when others then
      p_status := 500;
      p_response := error_json(sqlerrm, 'SESSION_DETAIL_FAILED');
  end get_session;

  procedure delete_session(p_session_id in varchar2, p_admin_token in varchar2, p_response out clob, p_status out number) is
    l_session_id varchar2(128) := clean_id(p_session_id);
  begin
    if not is_admin(p_admin_token) then
      p_status := 401;
      p_response := error_json('Admin unlock is required to delete saved sessions.', 'ADMIN_AUTH_REQUIRED');
      return;
    end if;
    delete from nsdh_event_log where session_id = l_session_id;
    delete from nsdh_generated_outputs where session_id = l_session_id;
    delete from nsdh_score_results where session_id = l_session_id;
    delete from nsdh_session_inputs where session_id = l_session_id;
    delete from nsdh_sessions where session_id = l_session_id;
    commit;
    p_status := 200;
    p_response := '{"ok":true,"deleted":' || apex_json.stringify(l_session_id) || '}';
  exception
    when others then
      rollback;
      p_status := 500;
      p_response := error_json(sqlerrm, 'SESSION_DELETE_FAILED');
  end delete_session;
end nsdh_log_api;
/

begin
  begin
    ords.delete_module(p_module_name => 'nsdh_api');
  exception
    when others then null;
  end;

  ords.define_module(
    p_module_name => 'nsdh_api',
    p_base_path => 'nsdh/',
    p_items_per_page => 25,
    p_status => 'PUBLISHED'
  );

  ords.define_template(p_module_name => 'nsdh_api', p_pattern => 'sessions');
  ords.define_handler(
    p_module_name => 'nsdh_api',
    p_pattern => 'sessions',
    p_method => 'POST',
    p_source_type => ords.source_type_plsql,
    p_source => q'[
declare
  l_response clob;
  l_status number;
begin
  nsdh_log_api.log_session(:body_text, l_response, l_status);
  :status_code := l_status;
  owa_util.mime_header('application/json', false);
  htp.p('Cache-Control: no-store');
  owa_util.http_header_close;
  htp.prn(l_response);
end;
]'
  );
  ords.define_handler(
    p_module_name => 'nsdh_api',
    p_pattern => 'sessions',
    p_method => 'GET',
    p_source_type => ords.source_type_plsql,
    p_source => q'[
declare
  l_response clob;
  l_status number;
begin
  nsdh_log_api.list_sessions(:search, :status, :audience, :strategy, :sort, coalesce(owa_util.get_cgi_env('HTTP_X_NSDH_APEX_ADMIN_TOKEN'), :admin_token), l_response, l_status);
  :status_code := l_status;
  owa_util.mime_header('application/json', false);
  htp.p('Cache-Control: no-store');
  owa_util.http_header_close;
  htp.prn(l_response);
end;
]'
  );

  ords.define_template(p_module_name => 'nsdh_api', p_pattern => 'sessions/:session_id');
  ords.define_handler(
    p_module_name => 'nsdh_api',
    p_pattern => 'sessions/:session_id',
    p_method => 'GET',
    p_source_type => ords.source_type_plsql,
    p_source => q'[
declare
  l_response clob;
  l_status number;
begin
  nsdh_log_api.get_session(:session_id, coalesce(owa_util.get_cgi_env('HTTP_X_NSDH_APEX_ADMIN_TOKEN'), :admin_token), l_response, l_status);
  :status_code := l_status;
  owa_util.mime_header('application/json', false);
  htp.p('Cache-Control: no-store');
  owa_util.http_header_close;
  htp.prn(l_response);
end;
]'
  );
  ords.define_handler(
    p_module_name => 'nsdh_api',
    p_pattern => 'sessions/:session_id',
    p_method => 'DELETE',
    p_source_type => ords.source_type_plsql,
    p_source => q'[
declare
  l_response clob;
  l_status number;
begin
  nsdh_log_api.delete_session(:session_id, coalesce(owa_util.get_cgi_env('HTTP_X_NSDH_APEX_ADMIN_TOKEN'), :admin_token), l_response, l_status);
  :status_code := l_status;
  owa_util.mime_header('application/json', false);
  htp.p('Cache-Control: no-store');
  owa_util.http_header_close;
  htp.prn(l_response);
end;
]'
  );

  ords.define_template(p_module_name => 'nsdh_api', p_pattern => 'admin/login');
  ords.define_handler(
    p_module_name => 'nsdh_api',
    p_pattern => 'admin/login',
    p_method => 'POST',
    p_source_type => ords.source_type_plsql,
    p_source => q'[
declare
  l_response clob;
  l_status number;
begin
  nsdh_log_api.admin_login(:body_text, l_response, l_status);
  :status_code := l_status;
  owa_util.mime_header('application/json', false);
  htp.p('Cache-Control: no-store');
  owa_util.http_header_close;
  htp.prn(l_response);
end;
]'
  );

  ords.define_template(p_module_name => 'nsdh_api', p_pattern => 'admin/logout');
  ords.define_handler(
    p_module_name => 'nsdh_api',
    p_pattern => 'admin/logout',
    p_method => 'POST',
    p_source_type => ords.source_type_plsql,
    p_source => q'[
declare
  l_response clob;
  l_status number;
begin
  nsdh_log_api.admin_logout(coalesce(owa_util.get_cgi_env('HTTP_X_NSDH_APEX_ADMIN_TOKEN'), :admin_token), l_response, l_status);
  :status_code := l_status;
  owa_util.mime_header('application/json', false);
  htp.p('Cache-Control: no-store');
  owa_util.http_header_close;
  htp.prn(l_response);
end;
]'
  );
  commit;
end;
/
